// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbbuvheymcqnzalfbmhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYnV2aGV5bWNxbnphbGZibWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjY4NDksImV4cCI6MjA3MzAwMjg0OX0.GxpOx_2-9KJwjQmnZZx53uX4dajz5VTp49oiu4JE7f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});